### ISSUE TITLE
feature: Add configuration mechanism

### ISSUE THREAD

**Issue by setrofim** [veraison/veraison#32] opened 2021-03-10 15:47 UTC
### Is your feature request related to a problem? Please describe

There is currently no easy way to provide configuration for Veraison components. Some components do have their own "Config" objects, but no standard mechanism is provided for populating them. A lot of them share some of the fields (e.g. path to plugin binaries), so it would make sense to provide them separately.

### If possible, describe a solution

Implement a configuration management component that will allow reading configuration form a standard format file (e.g YAML) and pass the relevant data to the other components.

### Describe alternatives you have considered

Consider using https://github.com/spf13/viper

### Additional context

N/A

**Comment by yogeshbdeshpande** [comment] 2022-11-15 09:38
The issue is already addressed in the new veraison/services repository.

Config is passed properly using Viper with a set of common utility functions.

**Closed by yogeshbdeshpande** 2022-11-15 09:38 UTC
Labels: enhancement
